- title: "文件菜单_1"
  target: "file"
  cmd: "notepad.exe"
- title: "文件菜单_2"
  target: "file"
  cmd: "notepad.exe"
- title: "文件菜单_3"
  target: "file"
  cmd: "notepad.exe"
- title: "文件夹菜单_1"
  target: "directory"
  cmd: "notepad.exe"
- title: "文件夹菜单_2"
  target: "directory"
  cmd: "notepad.exe"
- title: "文件夹菜单_3"
  target: "directory"
  cmd: "notepad.exe"
- title: "文件夹空白处菜单_1"
  target: "backgroud"
  cmd: "notepad.exe"
- title: "文件夹空白处菜单_2"
  target: "backgroud"
  cmd: "notepad.exe"
- title: "文件夹空白处菜单_2"
  target: "backgroud"
  cmd: "notepad.exe"
  submenu:
    - title: "子菜单项"
      target: "directory"
      cmd: "cmd.exe"
