- Title: "示例"
  Submenu:  
    - Title: "文件菜单示例_使用NotePad打开文件"
      Target: "file"
      Cmd: "notepad.exe"
    - Title: "文件夹菜单示例_显示属性"
      Target: "directory"
      Cmd: "example\\show_file_attributes.bat"
    - Title: "文件空白处菜单示例_显示当前路径"
      Target: "background"
      Cmd: "example\\show_current_path.bat"
    - Title: "综合示例_复制路径"
      Target: "background,file,directory"
      Cmd: "example\\copy_path_and_escape.bat"
